language: node_js

node_js: 
  - 13

services:
  - docker

script:
  
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy  

  # Tagging
  - docker tag udagram-api-feed nhatkhanh9a3/udagram-api-feed:v1
  - docker tag udagram-api-user nhatkhanh9a3/udagram-api-user:v1
  - docker tag udagram-frontend nhatkhanh9a3/udagram-frontend:v1a
  - docker tag reverseproxy nhatkhanh9a3/reverseproxy:v1
  - docker image ls
after_success:
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  # Login Docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Pushing 
  - docker push nhatkhanh9a3/udagram-api-feed:v1
  - docker push nhatkhanh9a3/udagram-api-user:v1
  - docker push nhatkhanh9a3/udagram-frontend:v1a
  - docker push nhatkhanh9a3/reverseproxy:v1